export const GENERIC_EQUIPMENTS = [
  { reference: 'LOK-BOARDBAG-OPT', name: 'Location Boardbag opt.', category: 'Accessoires', quantity: 10 },
  { reference: 'LOK-PACK-KITE', name: 'Location Pack Kitesurf - à personnaliser', category: 'Kitesurf', quantity: 10 },
  { reference: 'LOK-AILE-BARRE', name: 'Location Aile + Barre', category: 'Kitesurf', quantity: 10 },
  { reference: 'LOK-PACK-2AILES-BARRE', name: 'Location Pack 2 Ailes + Barre', category: 'Kitesurf', quantity: 10 },
  { reference: 'LOK-BOARD-TWINTIP', name: 'Location Planche Twintip', category: 'Kitesurf', quantity: 10 },
  { reference: 'LOK-WING-AILE', name: 'Location Aile de Wing', category: 'Wingfoil', quantity: 10 },
  { reference: 'LOK-HARNAIS-CULOTTE', name: 'Location Harnais culotte', category: 'Accessoires', quantity: 10 },
  { reference: 'LOK-AILE-SANSBARRE', name: 'Location Deuxième aile (sans barre)', category: 'Kitesurf', quantity: 10 },
  { reference: 'LOK-NEOPRENE-COMBINAISON', name: 'Location Combinaison', category: 'Néoprène', quantity: 10 },
  { reference: 'LOK-PACK-WING-GONFLABLE', name: 'Location Pack Wing gonflable', category: 'Wingfoil', quantity: 10 },
  { reference: 'LOK-NEOPRENE-CAGOULE', name: 'Location Cagoule', category: 'Néoprène', quantity: 10 },
  { reference: 'LOK-PACK-WING-RIGIDE', name: 'Location Pack Wing rigide', category: 'Wingfoil', quantity: 10 },
  { reference: 'LOK-PACK-WING-DEBUTANT', name: 'Location Pack Wing débutant', category: 'Wingfoil', quantity: 10 },
  { reference: 'LOK-WING-FOIL', name: 'Location Foil de Wing', category: 'Wingfoil', quantity: 10 },
  { reference: 'LOK-WING-BOARD', name: 'Location Planche de Wing', category: 'Wingfoil', quantity: 10 },
  { reference: 'LOK-WING-2AILE', name: 'Location Deuxième Aile de Wing', category: 'Wingfoil', quantity: 10 },
  { reference: 'LOK-CAGOULE-OPT', name: 'Location Cagoule opt.', category: 'Néoprène', quantity: 10 },
  { reference: 'LOK-CHAUSSONS-OPT', name: 'Location Chaussons opt.', category: 'Néoprène', quantity: 10 },
  { reference: 'LOK-GANTS-OPT', name: 'Location Gants opt.', category: 'Néoprène', quantity: 10 },
  { reference: 'LOK-HARNAIS-CEINTURE', name: 'Location Harnais ceinture', category: 'Accessoires', quantity: 10 },
  { reference: 'LOK-NEOPRENE-VESTE', name: 'Location Veste néoprène', category: 'Néoprène', quantity: 10 },
  { reference: 'LOK-NEOPRENE-CHAUSSONS', name: 'Location Chaussons', category: 'Néoprène', quantity: 10 },
  { reference: 'LOK-COMBINAISON-OPT', name: 'Location Combinaison opt.', category: 'Néoprène', quantity: 10 },
  { reference: 'LOK-BOARDBAG', name: 'Location Boardbag', category: 'Accessoires', quantity: 10 },
  { reference: 'LOK-NEOPRENE-GANTS', name: 'Location Gants', category: 'Néoprène', quantity: 10 },
  { reference: 'LOK-HARNAIS-CEINTURE-OPT', name: 'Location Harnais ceinture opt.', category: 'Accessoires', quantity: 10 },
  { reference: 'LOK-PROT-CASQUE', name: 'Location Casque', category: 'Protections', quantity: 10 },
  { reference: 'LOK-VESTENEOPRENE-OPT', name: 'Location Veste Néoprène opt.', category: 'Néoprène', quantity: 10 },
  { reference: 'LOK-PROT-GILET', name: 'Location Gilet', category: 'Protections', quantity: 10 },
  { reference: 'LOK-CASQUE-OPT', name: 'Location Casque opt.', category: 'Protections', quantity: 10 },
  { reference: 'LOK-GILET-OPT', name: 'Location Gilet opt.', category: 'Protections', quantity: 10 },
  { reference: 'LOK-HARNAIS-CULOTTE-OPT', name: 'Location Harnais Culotte opt.', category: 'Accessoires', quantity: 10 },
  { reference: 'LOK-3AILE-SANSBARRE', name: 'Location Troisième aile (sans barre)', category: 'Kitesurf', quantity: 10 },
  { reference: 'LOK-2AILE-SANSBARRE-CS', name: 'Location Deuxième aile (sans barre) - carte session', category: 'Carte Session', quantity: 10 },
  { reference: 'LOK-3AILE-SANSBARRE-CS', name: 'Location Troisième aile (sans barre) - carte session', category: 'Carte Session', quantity: 10 },
  { reference: 'LOK-TWINTIP-OPT-CS', name: 'Location Planche Twintip opt. - carte session', category: 'Carte Session', quantity: 10 },
  { reference: 'LOK-2WING-AILE-CS', name: 'Location Deuxième Aile de Wing - carte session', category: 'Carte Session', quantity: 10 },
  { reference: 'LOK-BARRE', name: 'Location Barre', category: 'Kitesurf', quantity: 10 },
  { reference: 'LOK-KITEFOIL', name: 'Location Kitefoil', category: 'Kitesurf', quantity: 10 },
  { reference: 'LOK-STRAPLESS', name: 'Location Strapless', category: 'Kitesurf', quantity: 10 },
  { reference: 'LOK-TWINTIP-OPT', name: 'Location Planche Twintip Opt.', category: 'Kitesurf', quantity: 10 },
  { reference: 'LOK-BOARD-FOIL-WING', name: 'Location Planche + Foil de Wing', category: 'Wingfoil', quantity: 10 },
  { reference: 'LOK-PADDLE', name: 'Location Paddle', category: 'Autres', quantity: 10 },
  { reference: 'LOK-SURF', name: 'Location Surf', category: 'Autres', quantity: 10 }
];
